sudo: false
dist: precise
language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test     # For gcc 4.9
      - kubuntu-backports           # For cmake 2.8.12
      - llvm-toolchain-precise-3.6  # For clang 3.6
    packages:
      - cmake
      - g++-4.9
      - clang-3.6

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./runUnitTests

after_success:
  - coveralls --root .. -E ".*submodules.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"

notifications:
  email: false
